# Generated by Django 6.0.2 on 2026-02-13 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_number', models.CharField(max_length=20)),
                ('customer_address', models.CharField(max_length=1000)),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bust', models.CharField(max_length=20)),
                ('waist', models.CharField(max_length=20)),
                ('hips', models.CharField(max_length=20)),
                ('shoulder_length', models.CharField(max_length=20)),
                ('sleeve_length', models.CharField(max_length=20)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer_mgt.customer')),
            ],
        ),
    ]
